# Introduction 

All chapters start with a first-level heading followed by your chapter title, like the line above. There should be only one first-level heading (`#`) per .Rmd file.

## E-device Working Group Overview

### Goals

In general, the goal of the electronic data entry sub-group of the DUWG is to research field data entry software and hardware devices (“e-devices”), and to generate resources that support IEP survey leads in selecting and deploying digital data-entry procedures.  This sub-group does not intend to suggest a single solution or software choice for all IEP surveys; rather, the sub-group aims to provide specific application reviews and testing, some methods development, and the start of an IEP e-device users network in effort to facilitate the independent decisions and potential transition of each IEP surveys to electronic data collection methods..

### Approach

A general approach to the exploration of e-device applications was outlined and agreed on at the initial e-device meetings.  

First, an e-device information gathering questionnaire (survey) would be distributed within IEP which specifically collects response data from: 1. Experienced e-device users, 2. Those who are currently researching e-device solutions for their survey applications; and 3. Those who have determined e-devices will not work for them. 

Second, following leads from the responses to the survey, this distribution is expanded to include external associates (ICF, NEON, CDFW Marine).  Follow-up interviews of the experienced e-device users and vendors are conducted, and demonstrations are arranged for the most promising e-device options.

Third, group members will potentially test specific e-devices apps by making use of free trial licenses, and these trials reported back to the group (SFBS & Yolo By-pass were early volunteers for trial forms development exercises).  Potentially other e-device methods will be researched and developed for demonstration purposes (e.g., collection and integration of external sensor data into e-device applications).


### Scope of group activities and intended products

The initial e-device questionnaire was used to identify the most common e-device apps used within IEP (Table 1), the key questions/concerns about using e-devices (section below), as well as the key criteria that will be used to evaluate each software options explored by the working group (Tables 2-7).  The main categories considering include options within the forms building tools, including QC related factors such as constrained choices and rules that guide subsequent fields.  Other categories include IT security protocols, photo integration, cost of different product options, and factors related to the business model of each vendor, including the longevity of the company and the level/cost of customer/technical support.  