# E-device Survey {#cross}

An Electronic Field Data-Entry Device ("e-Device") Survey was distributed to IEP survey leads in July of 2022. The goals of this survey were: 1. To get an understanding of the current level of use of electronic field data entry devices among IEP Survey Staff; 2. To seek information from expert e-device users about both hardware and software considerations, and 3. To the learn specific roadblocks for those who are hesitant to consider shifting to electronic data entry methods.  

Three groups were targeted for this survey:         
1. Experienced e-device users (internal IEP and external agencies),                            
2. IEP Survey Staff who are researching e-devices for field application,                                        
3. IEP Survey Staff who don't believe electronic field data collection will work for their application.

## Survey Respondents 

The IEP e-device survey was run for approximately a month and received 24 responses (Figure \@ref(fig:survey). A link to the original survey and to the compiled survey responses is included in the Appendix 2.   



```{r survey, echo = FALSE, include=TRUE, message=FALSE, warning=FALSE,  fig.cap='The distribution of of e-device survey responders by agency association. Most of these respondents were CDFW staff, but USFWS and DWR responses were also represented.  Two external agencies (NEON and ICF) were specifically asked to participate after survey responses pointed to these expert resources.',echo = FALSE, out.width='80%', fig.asp=.75, fig.align='center'}

source("setup.R")

sms <- Survey3  %>%  group_by(Agency) %>% summarize(n())
smssum <- Survey3  %>%  summarize(n())

pie_labels <- paste0(sms$Agency, " = ", round(100 *sms$`n()`/sum(sms$`n()`), 2), "%")
pie_labels <- paste0(sms$Agency, " = ", sms$`n()`)

pie(sms$`n()`, labels = pie_labels, col=c("#A9D18E", "#1B8CF0", "#E06F7D", "#D1BA26","#D3DEF1","#edd8e0"), 
    main= paste0("IEP E-device Survey Responses: Total = ", smssum),
    sub = "IEP Agencies not represented: SWRCB, NMFS, USEPA, USACE, USBR")

```

Among the 24 respondents, half of these were IEP associates and external contacts that are already using e-device applications for their survey data collections.  Five (20%) of the respondents were IEP associates who were currently seeking e-device solutions for their survey data collections. Two of the respondents indicated that they have already determined that electronic data entry would not work for their IEP survey application, and 5 respondents did not answer the question about their e-device use experience/status. An experienced e-device user resource list has been initiated, including contact names, software type, and type of survey application; this list will be expanded as possible (Appendix  ). 


