# Summary for Managers {-}

## Take Home Message: {-}

**IEP should transition to electronic data entry in order to improve efficiency and data quality.**

Digital data entry methods significantly increase the turn-around time of data from survey to publication by reducing field entry errors, eliminating manual entry QC checks, and improving overall processing efficiency. 



## Problem: {-}

**IEP still uses paper data sheets for most surveys.**  Several surveys have tried out different e-devices for collecting field data, but they haven't been broadly adopted and people are not sure which ones are best.  



## Method: {-}

The DUWG formed a sub-team and carried out the following steps:

1. **Polled IEP survey teams** to learn what digital data entry tools are currently used within the IEP network; 
2. **Evaluated the top software tools** with interviews/presentations from experienced users and product vendors; 
3. **Conducted software trials** using apps specifically configured for IEP survey data collections;
4. **Developed and Open-document forum** for exchange of technical information on e-devices across IEP;
5. **Summarized Pros and Cons** of the top e-device software options.


## Solutions: {-}

### 1. The Top Data Entry Software Apps Are Listed (Pros and Cons)  {-}

**The top software tools used for field data entry are listed and the Pros and Cons of each tool are briefly described.**

```{r proscons, echo = FALSE, include=TRUE, message=FALSE, warning=FALSE,  tab.cap='speakers', out.width='100%', tab.asp=.75, tab.align='left'}

library(kableExtra)
library(dplyr)
library(here)

pc<- as.data.frame(readRDS(here("proscons.rds"))) 

# Replace NAs with empty strings using replace()
pc[is.na(pc)] <- ""


pc %>%
  # Group by category column and collapse repeating values
  group_by(Software) %>%
  mutate(Software = ifelse(duplicated(Software), "", Software))  %>%

kable(pc, format = "html", escape = F, caption = "Summary Pros and Cons of the Top Field Data Entry Apps Reviewed.", booktabs = TRUE,align='l') %>%
  kable_paper() %>% 
  # kable_styling(bootstrap_options = c("striped", "hover"),full_width = FALSE, fixed_thead = TRUE,
  #               font_size = 20) %>%
  kable_styling(full_width =FALSE, fixed_thead = TRUE, font_size = 18) %>%
  #column_spec(1, width_min = "4cm", bold = TRUE, italic = F) %>%
  column_spec(1, width_max = "4.5cm", bold = TRUE, italic = F) %>%
  #column_spec(2, width_min = "6cm", bold = F, italic = F) %>%
  column_spec(2, width_max = "7cm", bold = F, italic = F) %>%
  #column_spec(3, width_min = "10cm", bold = F, italic = F) %>%
  column_spec(3, width_max = "10cm", bold = F, italic = F) %>%
  scroll_box(width = "800px")

```

### 2. An Open-access E-device Information Repository Is Available {-}

**An open-access repository for information related to electronic field data entry software/hardware for IEP Survey application has been developed**.  This document is intended as resource for IEP survey leads in selecting and deploying digital data-entry procedures. A Github-based bookdown framework has been established to support open sharing and on-going community updates as survey teams add new digital data-entry tools to their program.  


## Impact: {-}

Adopting digital data entry protocols will require time to develop the platforms and software and to train the staff. In addition, IEP surveys will have to budget for the purchase and maintenance of mobile field devices, data loggers and/or electronic fish measurement boards. **In the longer term,the time and staff-power savings in reduced data entry and post-collection processing will significantly out-weigh equipment and training time expenditures.**





